name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            echo "--- Building and starting up Docker ---"
            docker-compose -f ./SebastienGrard/sdv-m1do-containers-project/docker-compose.yml -p testing up -d --build
            echo "--- Containers up ---"

        - name: Push the Docker image
          id: push-docker-image
          run: |
            echo "--- Pushing the Docker image to Docker Hub ---"
            docker push "${{ secrets.DOCKERHUB_USERNAME }}/sdv-m1do-containers-project:latest"
      
